swagger: "2.0"
info:
  title: Walkdog Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: yunnet@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /wk_stores/{id}:
    get:
      tags:
      - wk_stores
      description: get WkStores by id
      operationId: WkStoresController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
        default: "1"
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.WkStores'
        "403":
          description: :id is empty
  /wk_stores/stores:
    get:
      tags:
      - wk_stores
      description: 获取商店中的商品
      operationId: WkStoresController.Get All
      parameters:
      - in: query
        name: level
        description: 当前用户等级
        required: true
        type: string
        default: "5"
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.WkStores'
        "403":
          description: ""
  /wk_stores/storesadvance:
    get:
      tags:
      - wk_stores
      description: 获取所有高级属性物品
      operationId: WkStoresController.Get All advance WkStores
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.WkStoresAdvance'
        "403":
          description: ""
  /wk_user/:
    get:
      tags:
      - wk_user
      description: get WkUser
      operationId: WkUserController.Get All
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.WkUser'
        "403":
          description: ""
  /wk_user/{id}:
    get:
      tags:
      - wk_user
      description: get WkUser by id
      operationId: WkUserController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
        default: "10001"
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.WkUser'
        "403":
          description: :id is empty
  /wk_user_status/{id}:
    put:
      tags:
      - wk_user_status
      description: update the WkUserStatus
      operationId: WkUserStatusController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
        default: "10001"
      - in: body
        name: body
        description: body for WkUserStatus content
        required: true
        schema:
          $ref: '#/definitions/models.WkUserStatus'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.WkUserStatus'
        "403":
          description: :id is not int
  /wk_user_status/GetByUID:
    get:
      tags:
      - wk_user_status
      description: 根据用户ID获取用户信息
      operationId: WkUserStatusController.Get One
      parameters:
      - in: query
        name: uid
        description: 用户ID
        required: true
        type: string
        default: "10001"
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.WkUserStatus'
        "403":
          description: ""
  /wk_user_status/GetStocksByUID:
    get:
      tags:
      - wk_user_status
      description: 根据用户ID获取仓库物品
      operationId: WkUserStatusController.Get One
      parameters:
      - in: query
        name: uid
        description: 用户ID
        required: true
        type: string
        default: "10001"
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.WkUserStatus'
        "403":
          description: ""
  /wk_user_status/UpdateGoldCoin:
    put:
      tags:
      - wk_user_status
      description: update the WkUserStatus
      operationId: WkUserStatusController.Update
      parameters:
      - in: query
        name: id
        description: The id you want to update
        required: true
        type: string
        default: "1"
      - in: query
        name: goldcoin
        description: gold coin
        required: true
        type: string
        default: "9999"
      responses:
        "403":
          description: ""
  /wk_user_status/UpdateGoods:
    put:
      tags:
      - wk_user_status
      description: update the WkUserStatus
      operationId: WkUserStatusController.Update
      parameters:
      - in: query
        name: id
        description: The id you want to update
        required: true
        type: string
        default: "1"
      - in: query
        name: pools
        description: pools
        required: true
        type: string
        default: 5,0,3,2,1,0,0,0,0,0,0,0
      responses:
        "403":
          description: ""
  /wk_user_status/UpdateStocks:
    put:
      tags:
      - wk_user_status
      description: update the WkUserStatus
      operationId: WkUserStatusController.Update
      parameters:
      - in: query
        name: id
        description: The id you want to update
        required: true
        type: string
        default: "1"
      - in: query
        name: pools
        description: pools
        required: true
        type: string
        default: 5,0,3,2,1,0,0,0,0,0,0,0
      - in: query
        name: stocks
        description: stocks
        required: true
        type: string
        default: (3,1),(1,3)
      responses:
        "403":
          description: ""
definitions:
  models.WkStores:
    title: WkStores
    type: object
    properties:
      GoodName:
        description: 商品名称
        type: string
      Id:
        description: 序号
        type: integer
        format: int64
      Multiple1:
        description: 商品价格倍数
        type: integer
        format: int64
      Multiple2:
        description: 速率倍数
        type: integer
        format: int64
      Price:
        description: 商品价格
        type: number
        format: double
      Readonly:
        description: 是否可用
        type: integer
        format: int64
      SpeedRate:
        description: 速率
        type: number
        format: double
  models.WkStoresAdvance:
    title: WkStoresAdvance
    type: object
    properties:
      GoodName:
        description: 商品名称
        type: string
      Id:
        description: 序号
        type: integer
        format: int64
      Memo1:
        description: 备注1
        type: string
      Memo2:
        description: 备注2
        type: string
  models.WkUser:
    title: WkUser
    type: object
    properties:
      Avatar:
        description: 用户头像
        type: string
      Ctime:
        description: 添加时间
        type: integer
        format: int64
      Email:
        description: 邮箱
        type: string
      Id:
        description: 序号
        type: integer
        format: int64
      Intro:
        description: 简介
        type: string
      Password:
        description: 用户密码
        type: string
      Phone:
        description: 手机号
        type: string
      Salt:
        description: 用户随机码
        type: string
      Status:
        type: integer
        format: int64
      UserName:
        description: 用户名
        type: string
  models.WkUserStatus:
    title: WkUserStatus
    type: object
    properties:
      CTime:
        description: 添加时间
        type: integer
        format: int64
      Goldcoin:
        description: 金币
        type: integer
        format: int64
      Id:
        description: 序号
        type: integer
        format: int64
      Level:
        description: 用户等级
        type: integer
        format: int64
      ParentUid:
        description: 用户上级
        type: integer
        format: int64
      Pools:
        description: 用户池
        type: string
      Stocks:
        description: 仓库
        type: string
      Stocksize:
        description: 仓库大小
        type: integer
        format: int64
      UTime:
        description: 修改时间
        type: integer
        format: int64
      Uid:
        description: 用户序号
        type: integer
        format: int64
tags:
- name: home
  description: |
    主要入口
